name: rule_rush
description: "this project for self-study road rules"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  go_router: ^12.1.1
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  lucide_icons_flutter: ^1.2.8
  carousel_slider: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/tests/parse_ru_RU/
    - assets/tests/parse_ru_RU/1/
    - assets/tests/parse_ru_RU/2/
    - assets/tests/parse_ru_RU/3/
    - assets/tests/parse_ru_RU/4/
    - assets/tests/parse_ru_RU/5/
    - assets/tests/parse_ru_RU/6/
    - assets/tests/parse_ru_RU/7/
    - assets/tests/parse_ru_RU/8/
    - assets/tests/parse_ru_RU/9/
    - assets/tests/parse_ru_RU/10/
    - assets/tests/parse_ru_RU/11/
    - assets/tests/parse_ru_RU/12/
    - assets/tests/parse_ru_RU/13/
    - assets/tests/parse_ru_RU/14/
    - assets/tests/parse_ru_RU/15/
    - assets/tests/parse_ru_RU/16/
    - assets/tests/parse_ru_RU/17/
    - assets/tests/parse_ru_RU/18/
    - assets/tests/parse_ru_RU/19/
    - assets/tests/parse_ru_RU/20/
    - assets/tests/parse_ru_RU/21/
    - assets/tests/parse_ru_RU/22/
    - assets/tests/parse_ru_RU/23/
    - assets/tests/parse_ru_RU/24/
    - assets/tests/parse_ru_RU/25/
    - assets/tests/parse_ru_RU/26/
    - assets/tests/parse_ru_RU/27/
    - assets/tests/parse_ru_RU/28/
    - assets/tests/parse_ru_RU/29/
    - assets/tests/parse_ru_RU/30/
    - assets/tests/parse_ru_RU/31/
    - assets/tests/parse_ru_RU/32/
    - assets/tests/parse_ru_RU/33/
    - assets/tests/parse_ru_RU/34/
    - assets/tests/parse_ru_RU/35/

  uses-material-design: true

